pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp index.html public/
    - cp -r assets public/
    - cp -r src public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
